"""
clean_documents.py
==================

The CLEANING stage of "The Unofficial CS Career Guide" RAG pipeline.

It reads the raw snapshot produced by load_documents.py (raw_documents.json),
strips out everything that is NOT substantive content, and writes the result
to cleaned_documents.json.

WHAT WE REMOVE (clutter / boilerplate that appears on the page but isn't advice):
    - HTML tags and HTML entities (&nbsp;, &amp;, ...)
    - navigation menus, "Explore related questions", "Related Articles"
    - cookie/promo banners, ads ("Promoted")
    - footers and legal boilerplate ("The information on this site is ...")
    - "Read more" / "Show more" links, share buttons, comment counts
    - Reddit/Medium/Stack Exchange UI chrome (Upvote, Reply, "4 min read",
      "13y ago", usernames, clap/subscribe calls-to-action, related-post teasers)

WHAT WE KEEP:
    - the actual discussion text, opinions, advice, explanations, code, and
      any context needed to understand it (titles, course/subject names, etc.)

IMPORTANT SAFEGUARD:
    We only strip *known* HTML tag names. Some documents contain things like
    `MutableLiveData<Cart>` in code, and a naive "<...>" remover would delete
    `<Cart>` and corrupt the sentence. Whitelisting real tags avoids that.

After running, the script prints ONE full cleaned document so you can read it
and check for leftover clutter.
"""

import html
import json
import re
from pathlib import Path

INPUT_FILE = Path("raw_documents.json")
OUTPUT_FILE = Path("cleaned_documents.json")

# Which document to print for inspection (by doc_id). Indeed has the most
# footer/nav boilerplate, so it's a good stress test.
INSPECT_DOC_ID = "11_indeed_proj_rec"


# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------

# Only strip REAL html tags (whitelist) so code like `MutableLiveData<Cart>`
# is left alone.
KNOWN_HTML_TAGS = re.compile(
    r"</?(?:a|abbr|b|blockquote|br|button|code|div|em|figure|figcaption|"
    r"footer|form|h[1-6]|header|hr|i|img|input|label|li|main|nav|ol|p|pre|"
    r"section|small|span|strong|sub|sup|svg|path|table|tbody|td|th|thead|tr|"
    r"u|ul)(?:\s[^>]*)?/?>",
    re.IGNORECASE,
)

# Full-line clutter, compared in lowercase after stripping. One UI label per line.
CLUTTER_LINES = {
    # generic reddit/forum chrome
    "upvote", "downvote", "reply", "share", "share:", "save", "report",
    "award", "follow", "following", "report comment", "go to comments",
    "join the conversation", "sort by:", "best", "top", "new", "controversial",
    "old", "q&a", "comments section", "search comments", "expand comment search",
    "add a comment", "more replies", "more replies...", "view replies",
    "promoted", "listen", "·", "•", "—", "level up coding", "follow publication",
    "press enter or click to view image in full size", "sign up", "log in",
    "open in app", "edit", "edited", "deleted", "[deleted]", "[removed]",
    "show more", "see more", "read more", "continue reading", "written by",
    # stack exchange footer / nav / per-answer chrome
    "start asking to get answers", "find the answer to your question by asking.",
    "explore related questions", "see similar questions with these tags.",
    "learningeducation", "improve this answer", "share improve this answer",
    "community wiki", "follow this answer", "add a comment",
    # indeed footer / nav / search widget
    "generated by ai and may contain mistakes.", "related articles",
    "explore more articles", "search jobs and companies hiring now",
    "job title, keywords or company", "location",
    # medium footer / nav / inline subscribe widget
    "to access my other articles:", "you can reach me from the links below:",
    "linkedin", "instagram", "twitter", "facebook", "medium.com",
    "enter your email", "subscribe", "remember me for faster sign in",
}

# Full-line clutter described by regular expressions (things that vary).
CLUTTER_PATTERNS = [
    re.compile(r"^u/\S+.*$", re.IGNORECASE),               # "u/name", "u/name avatar"
    re.compile(r"^r/\S+$", re.IGNORECASE),                 # bare subreddit links
    re.compile(r"^-?\d+$"),                                # standalone vote/score numbers ("5", "-2")
    re.compile(r"^(answered|asked|edited)\s+[a-z]+\s+\d{1,2},?\s+\d{4}.*$", re.IGNORECASE),  # SE "answered Jan 5, 2011 at 17:12"
    re.compile(r"^\d+\s*(min|minute)s?\s+read$", re.IGNORECASE),    # "4 min read"
    re.compile(r"^\d+\s*(y|yr|yrs|mo|w|d|h|hr|hrs|m|s)\s*\.?\s*ago$", re.IGNORECASE),  # "13y ago"
    re.compile(r"^\d{1,3}([.,]\d{3})*\s*(points?|upvotes?|comments?|votes?)$", re.IGNORECASE),
    re.compile(r"^thumbnail image:.*$", re.IGNORECASE),    # image captions
    re.compile(r"^\d+\s+more\s+repl(y|ies).*$", re.IGNORECASE),     # "8 more replies"
    re.compile(r"^this post was mass deleted.*$", re.IGNORECASE),   # Redact notice
    re.compile(r"^commented.*\d{4}.*$", re.IGNORECASE),    # "CommentedJan 5, 2011 at 16:05"
    re.compile(r"^slide\s*\d+\s*of\s*\d+$", re.IGNORECASE),         # "slide 1 of 12"
    re.compile(r"^slide\d+\s*of\s*\d+$", re.IGNORECASE),            # "slide1 of 12"
    re.compile(r"^\d+\s*/\s*\d+$"),                        # "1 / 12"
    re.compile(r"^read more:.*$", re.IGNORECASE),          # "Read more: ..." link lists
    re.compile(r"^related:.*$", re.IGNORECASE),            # "Related: ..." link lists
    re.compile(r"^updated\s+[a-z]+\s+\d{1,2},\s+\d{4}$", re.IGNORECASE),  # "Updated December 11, 2025"
    re.compile(r"^closed\s+\d+\s+years?\s+ago\.?$", re.IGNORECASE),       # SE "Closed 11 years ago."
]

# Substring markers: if any appears in a line, drop the whole line. Use for
# boilerplate sentences that are easy to identify by a unique phrase.
CLUTTER_CONTAINS = [
    "the information on this site is provided as a courtesy",
    "indeed is not a career or legal advisor",
    "resumes & cover letters",
    "clap the story",
    "subscribe my free newsletter",
    "if you are not a member, you can access",
    "form a foundation for a career in ai with hands-on",
    "check out live virtual bootcamps",
    # indeed promo / app ads
    "career scout", "personal ai career coach", "only available on the app",
    "source: indeed data", "based on employee reviews on indeed",
    "what do employees say about working at", "recognized by indeed users",
    # medium inline subscribe widget
    "stories in your inbox", "join medium for free", "remember me for faster",
    # stack exchange close-reason boilerplate
    "off topic on programmers", "the whiteboard, our chat room",
    "off topic here. they are only meaningful to the asker",
]

# If a line contains one of these footer markers, drop that line AND everything
# after it. These mark the start of trailing widgets (related posts, company
# blurbs, author sign-offs) that contain no domain content.
TRUNCATE_AT_MARKERS = [
    "top 5 highly rated software companies",   # indeed company-review widget
    "thanks for coming this far",              # medium author sign-off + teasers
    "to access my other articles",             # medium related-post teasers
]


def strip_leading_symbols(line):
    """Drop leading emoji / bullet symbols so '👨‍💼 Linkedin' matches 'linkedin'."""
    return re.sub(r"^[\W_]+", "", line).strip()


def is_clutter(line):
    """Return True if a single line is non-content clutter."""
    lowered = line.lower()
    if lowered in CLUTTER_LINES:
        return True
    # also test the line with leading emoji/symbols removed
    if strip_leading_symbols(lowered) in CLUTTER_LINES:
        return True
    if any(pattern.match(line) for pattern in CLUTTER_PATTERNS):
        return True
    if any(marker in lowered for marker in CLUTTER_CONTAINS):
        return True
    return False


def clean_text(text):
    """Turn one document's raw text into clean, content-only text."""
    # 1) Decode HTML entities first: &nbsp; -> space, &amp; -> &, etc.
    text = html.unescape(text)
    # html.unescape turns &nbsp; into a non-breaking space (\xa0); make it normal.
    text = text.replace("\xa0", " ")

    # 2) Remove real HTML tags (whitelist keeps `<Cart>`-style content safe).
    text = KNOWN_HTML_TAGS.sub("", text)

    # 3) Go line by line, normalising whitespace and dropping clutter lines.
    kept_lines = []
    for line in text.splitlines():
        line = re.sub(r"[ \t]+", " ", line).strip()

        # Stop entirely once we hit a trailing-footer marker.
        lowered = line.lower()
        if any(marker in lowered for marker in TRUNCATE_AT_MARKERS):
            break

        if not line:
            kept_lines.append("")          # keep blank lines for now; collapsed below
            continue
        if is_clutter(line):
            continue
        kept_lines.append(line)

    # 4) Collapse 3+ blank lines into a single blank line, trim the ends.
    cleaned = "\n".join(kept_lines)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def main():
    if not INPUT_FILE.exists():
        raise SystemExit(f"'{INPUT_FILE}' not found. Run load_documents.py first.")

    documents = json.loads(INPUT_FILE.read_text(encoding="utf-8"))

    cleaned_docs = []
    for doc in documents:
        cleaned_text = clean_text(doc["raw_text"])
        cleaned_docs.append({
            "doc_id": doc["doc_id"],
            "source_filename": doc["source_filename"],
            "source_path": doc["source_path"],
            "title": doc["title"],
            "url": doc["url"],
            "source_type": doc["source_type"],
            "raw_char_count": doc["char_count"],
            "clean_char_count": len(cleaned_text),
            "cleaned_text": cleaned_text,
        })

    OUTPUT_FILE.write_text(
        json.dumps(cleaned_docs, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # Summary
    print("=" * 60)
    print("CLEANING SUMMARY")
    print("=" * 60)
    print(f"Documents cleaned : {len(cleaned_docs)}")
    print(f"Saved to          : {OUTPUT_FILE}")
    print("-" * 60)
    for doc in cleaned_docs:
        before, after = doc["raw_char_count"], doc["clean_char_count"]
        removed_pct = (1 - after / before) * 100 if before else 0
        print(f"  {doc['source_filename']:35s} "
              f"{before:>7,d} -> {after:>7,d} chars  (-{removed_pct:4.1f}%)")

    # Print ONE full document for manual inspection.
    sample = next((d for d in cleaned_docs if d["doc_id"] == INSPECT_DOC_ID),
                  cleaned_docs[0])
    print("\n" + "=" * 60)
    print(f"FULL CLEANED DOCUMENT FOR INSPECTION: {sample['source_filename']}")
    print(f"  title: {sample['title']}")
    print(f"  type : {sample['source_type']}")
    print("=" * 60)
    print(sample["cleaned_text"])


if __name__ == "__main__":
    main()
